"""Regenerate the wheel's fixed Terraform fixtures from the repository examples."""

from pathlib import Path
from pprint import pformat

from blastradius.scenarios import SCENARIOS


def main() -> None:
    fixtures = {}
    for scenario in SCENARIOS:
        fixtures[scenario.id] = {
            "title": scenario.title,
            "root_cause": scenario.root_cause,
            "change": scenario.change,
            "before_files": {
                p.name: p.read_text(encoding="utf-8") for p in sorted(scenario.before.glob("*.tf"))
            },
            "after_files": {
                p.name: p.read_text(encoding="utf-8") for p in sorted(scenario.after.glob("*.tf"))
            },
        }
    Path(__file__).with_name("fixtures.py").write_text(
        '"""Generated by python -m blastradius.server.bundle_demos; real offline fixtures."""\n\n'
        + "from blastradius.server.fixture_types import DemoFixture\n\n"
        + "FIXTURES: dict[str, DemoFixture] = "
        + pformat(fixtures, width=100, sort_dicts=True)
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
