"""commercial beta foundation

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 20:49:58.621342

"""

from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE memberships SET role = 'developer' WHERE role = 'member'")
    with op.batch_alter_table("memberships") as batch_op:
        batch_op.create_check_constraint(
            "membership_role", "role IN ('owner', 'admin', 'developer', 'viewer')"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_org_created", ["organization_id", "created_at"], unique=False
        )

    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("revoked_at", sa.Float(), nullable=True),
        sa.Column("accepted_at", sa.Float(), nullable=True),
        sa.CheckConstraint("role IN ('admin', 'developer', 'viewer')", name="invitation_role"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_invitations_org_expiry", ["organization_id", "expires_at"], unique=False
        )

    op.create_table(
        "analysis_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id", "format"),
    )
    with op.batch_alter_table("analysis_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_artifacts_analysis_id"), ["analysis_id"], unique=False
        )

    op.create_table(
        "attack_paths",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("path_key", sa.Text(), nullable=False),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("reaches_sensitive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attack_paths", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attack_paths_analysis_id"), ["analysis_id"], unique=False
        )

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_analysis_id"), ["analysis_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_severity"), ["severity"], unique=False)

    op.create_table(
        "attack_path_hops",
        sa.Column("path_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_node", sa.Text(), nullable=False),
        sa.Column("target_node", sa.Text(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["path_id"], ["attack_paths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("path_id", "position"),
    )
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("input_type", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("base_ref", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("candidate_ref", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("base_sha", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("candidate_sha", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("decision", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("score_before", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("score_after", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("risk_before", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("risk_after", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("critical_paths_added", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("critical_paths_removed", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("normalized_version", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("policy_snapshot", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("request_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_analyses_candidate_ref"), ["candidate_ref"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analyses_decision"), ["decision"], unique=False)
        batch_op.create_index(
            "ix_analyses_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_analyses_project_created", ["project_id", "created_at"], unique=False
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plan_limits", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("policy", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("policy_version", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("updated_at", sa.Float(), nullable=True))

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), server_default="", nullable=False))
        batch_op.add_column(
            sa.Column("repository", sa.String(length=255), server_default="", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "repository_provider", sa.String(length=20), server_default="manual", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "default_branch", sa.String(length=120), server_default="main", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("environment", sa.String(length=100), server_default="", nullable=False)
        )
        batch_op.add_column(
            sa.Column("terraform_root", sa.String(length=255), server_default=".", nullable=False)
        )
        batch_op.add_column(sa.Column("archived_at", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("policy", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("policy_version", sa.Integer(), server_default="0", nullable=False)
        )

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.Float(), nullable=True))
        batch_op.create_unique_constraint("uq_sessions_id", ["id"])

    connection = op.get_bind()
    for row in connection.execute(sa.text("SELECT token_hash FROM sessions")):
        connection.execute(
            sa.text("UPDATE sessions SET id = :id WHERE token_hash = :token"),
            {"id": str(uuid.uuid4()), "token": row[0]},
        )

    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("exports", sa.Integer(), server_default="0", nullable=False))

    op.add_column(
        "users",
        sa.Column("email_verified", sa.Boolean(), server_default=sa.false(), nullable=False),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError(
        "Restore a pre-upgrade backup to return to 0001; beta evidence cannot be downgraded."
    )
