"""github_app

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-19 21:13:58.649408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_deliveries",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("body_hash"),
    )
    op.create_table(
        "github_installations",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("verified_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("github_installations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_github_installations_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "repository_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["github_installations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "repository_id"),
        sa.UniqueConstraint("project_id"),
        sa.UniqueConstraint("repository_id"),
    )
    with op.batch_alter_table("repository_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repository_connections_installation_id"),
            ["installation_id"],
            unique=False,
        )

    op.create_table(
        "github_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=True),
        sa.Column("pull_number", sa.Integer(), nullable=False),
        sa.Column("base_sha", sa.String(length=40), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("head_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("base_ref", sa.String(length=120), nullable=False),
        sa.Column("head_ref", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.Column("check_id", sa.BigInteger(), nullable=True),
        sa.Column("check_uncertain", sa.Boolean(), nullable=False),
        sa.Column("comment_uncertain", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["repository_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id"),
    )
    with op.batch_alter_table("github_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_github_runs_connection_id"), ["connection_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("github_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_github_runs_connection_id"))

    op.drop_table("github_runs")
    with op.batch_alter_table("repository_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_connections_installation_id"))

    op.drop_table("repository_connections")
    with op.batch_alter_table("github_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_github_installations_organization_id"))

    op.drop_table("github_installations")
    op.drop_table("github_deliveries")
    # ### end Alembic commands ###
