"""beta_feedback_events

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-20 12:06:30.315809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, Sequence[str], None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beta_interest",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("company", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=False),
        sa.Column("team_size", sa.Integer(), nullable=True),
        sa.Column("repository_count", sa.Integer(), nullable=True),
        sa.Column("primary_cloud", sa.String(length=20), nullable=True),
        sa.Column("source_control", sa.String(length=20), nullable=True),
        sa.Column("problem", sa.String(length=1000), nullable=False),
        sa.Column("privacy_version", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("beta_interest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_beta_interest_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "commercial_lock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(sa.table("commercial_lock", sa.column("id", sa.Integer())), [{"id": 1}])
    op.create_table(
        "analysis_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("useful", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id", "user_id"),
    )
    with op.batch_alter_table("analysis_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_feedback_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_feedback_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "product_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("analysis_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_product_events_name"), ["name"], unique=False)

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("oidc_authenticated", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_column("oidc_authenticated")

    with op.batch_alter_table("product_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_events_name"))
        batch_op.drop_index(batch_op.f("ix_product_events_created_at"))

    op.drop_table("product_events")
    with op.batch_alter_table("analysis_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_feedback_created_at"))
        batch_op.drop_index(batch_op.f("ix_analysis_feedback_analysis_id"))

    op.drop_table("analysis_feedback")
    op.drop_table("commercial_lock")
    with op.batch_alter_table("beta_interest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_beta_interest_created_at"))

    op.drop_table("beta_interest")
    # ### end Alembic commands ###
