import { Link } from 'react-router-dom';
import { ArrowRight, ExternalLink } from 'lucide-react';
import { PageHeading } from '../components/UI';

const repository = 'https://github.com/Mighiana/BlastRadius';
export default function Guide() {
  return <div className="container page guide"><PageHeading eyebrow="QUICK START" title="From Terraform to an informed decision.">Choose a local workflow, a pull request check, or an isolated workspace.</PageHeading>
    <div className="guide-grid"><aside className="panel guide-nav"><a href="#workspace">Upload a comparison</a><a href="#cli">Run the CLI</a><a href="#github">GitHub Actions</a><a href="#model">Understand coverage</a><a href="#privacy">Privacy & security</a></aside><div className="report-stack">
      <section className="panel" id="workspace"><span className="eyebrow">01 / WORKSPACE</span><h2>Your first comparison</h2><ol className="guide-steps"><li>Sign in with your configured identity provider, or create an explicit local demo workspace.</li><li>Create a project named after a repository or environment.</li><li>Upload baseline and candidate <code>.tf</code> files, or one <code>terraform show -json</code> plan. Choose meaningful labels.</li><li>Analyze the change. Open the report to inspect the decision, paths and evidence.</li><li>Review recommended edits, update candidate input and analyze again. Export evidence as JSON, Markdown or SARIF.</li></ol><Link to="/dashboard" className="button primary">Open workspace<ArrowRight size={16} aria-hidden="true" /></Link><p className="muted">No connected repository or GitHub App is required. This UI accepts uploaded content, never arbitrary server paths or execution commands.</p></section>
      <section className="panel" id="cli"><span className="eyebrow">02 / LOCAL CLI</span><h2>Keep source on your machine</h2><p>Requires Python 3.11 or later and Git. Run from a reviewed checkout of this repository.</p><pre><code>{'python -m venv .venv\nsource .venv/bin/activate\npython -m pip install .\n\npython -m blastradius.cli \\\n  --before examples/safe \\\n  --after examples/vulnerable \\\n  --format pr'}</code></pre><p>For a plan:</p><pre><code>{'terraform show -json your-plan.tfplan > plan.json\npython -m blastradius.cli --plan plan.json --format sarif'}</code></pre><p className="muted">Generate plans only in your trusted environment. BlastRadius reads plan JSON as data. Exit 0 passes the gate, 1 blocks, and 2 means invalid input or usage. REVIEW passes by default; use <code>--fail-on-review</code> to block it.</p></section>
      <section className="panel" id="github"><span className="eyebrow">03 / PULL REQUESTS</span><h2>Install the GitHub Actions check</h2><p>Use the repository’s reviewed consumer workflow. It installs an immutable analyzer revision, reads base/head snapshots and updates one bot comment with the decision and evidence.</p><ol className="guide-steps"><li>Copy the documented consumer workflow into your repository.</li><li>Set your Terraform root using trusted base configuration.</li><li>Use the <code>pull_request</code> event and minimal permissions. Never run candidate Terraform providers or contributor scripts.</li><li>Require the analysis check before merging. Keep report artifacts when PR comments are unavailable.</li></ol><a className="button secondary" href={`${repository}#github-actions`} target="_blank" rel="noreferrer">GitHub Actions instructions<ExternalLink size={16} aria-hidden="true" /></a><p className="muted">A GitHub App and automatic workspace history ingestion from Actions are not implemented. CLI reports remain in your CI artifacts and PR comment.</p></section>
      <section className="panel" id="model"><span className="eyebrow">04 / THE MODEL</span><h2>Evidence with explicit limits</h2><p>BlastRadius builds a static graph from supported Terraform relationships. Public ingress can reach compute, compute can assume roles, and roles can access storage marked sensitive.</p><p>Supported coverage is deliberately bounded. Modules, unresolved values, IAM conditions and other controls may reduce accuracy; each report carries coverage diagnostics. Read the repository documentation for the exact engine revision you run.</p><p>The 0–100 score is a transparent, capped heuristic for comparison. It is not a probability of compromise. A SAFE merge decision can coexist with existing exposure; it evaluates the change.</p><Link to="/demo" className="text-link">Inspect a real example<ArrowRight size={16} aria-hidden="true" /></Link></section>
      <section className="panel" id="privacy"><span className="eyebrow">05 / DATA HANDLING</span><h2>Know where your data goes</h2><p>Public demos use fixed fixtures. Workspace uploads are processed by your configured backend, and reports can retain source diffs and patched Terraform. Avoid secrets in uploads. Browser credentials stay in backend-managed HttpOnly cookies; the UI does not persist tokens in browser storage.</p><p>Deleting a history entry removes the stored analysis and report. It does not refund quota or erase external backups. There is no automatic retention schedule. Operators must set backup, retention and deletion policies before hosting customer data.</p><p>OIDC authentication and Stripe test mode require operator configuration. Legal terms, privacy policy, support contacts and production service commitments require owner review before commercial launch.</p><a href={`${repository}/security`} className="text-link" target="_blank" rel="noreferrer">Repository security information<ExternalLink size={16} aria-hidden="true" /></a></section>
    </div></div>
  </div>;
}
