import { Link } from 'react-router-dom';
import { PageHeading } from '../components/UI';

export default function Trust({ kind }: { kind: 'security' | 'privacy' | 'terms' }) {
  return <div className="container page guide"><PageHeading eyebrow="TRUST & TRANSPARENCY" title={kind === 'security' ? 'Security and its boundaries.' : kind === 'privacy' ? 'How workspace data is handled.' : 'Commercial beta terms.'}>Static analysis with explicit limits. Terms and policies are set by your deployment operator.</PageHeading>
    <div className="report-stack">
      {kind === 'security' ? <>
        <section className="panel"><h2>What a decision means</h2>
          <ul className="decision-legend">
            <li><span className="decision block">BLOCK CHANGE</span><span>A new modeled path from the internet to sensitive data, or a change your policy forbids (for example new public SSH).</span></li>
            <li><span className="decision review">REVIEW REQUIRED</span><span>New exposure that is not blocking, or something the model could not resolve. A human must look.</span></li>
            <li><span className="decision safe">SAFE TO MERGE</span><span>No new modeled path under the selected model and policy. Not proof that infrastructure is secure: existing exposure and coverage gaps may remain.</span></li>
          </ul>
          <p>Coverage of AWS networking, IAM and storage is bounded. Read every report’s coverage diagnostics; the score is a heuristic, not a probability of compromise.</p></section>
        <section className="panel"><h2>Execution and access</h2><p>Static analysis requires no AWS credentials and does not deploy infrastructure. Uploads and plan JSON are treated as data. The GitHub App reads immutable, bounded Terraform snapshots without executing contributor scripts, workflows or providers.</p><p>Authenticated workspace APIs enforce tenant membership and role authorization. Mutations require session and CSRF checks at the configured Origin. Session cookies are managed by the backend; the frontend keeps its CSRF token in memory.</p><p>GitHub requires contents:read, metadata:read, pull_requests:write and checks:write. Installation registration requires operator verification; installing the App alone does not claim a workspace.</p></section>
        <section className="panel"><h2>Report a vulnerability</h2><p>Report privately through GitHub Security Advisories for this repository. Do not post secrets or exploit details in public issues. Hosted deployments run by another operator: use that operator’s private channel.</p><div className="button-row"><a className="button primary" href="https://github.com/Mighiana/BlastRadius/security/advisories/new" target="_blank" rel="noreferrer">Report privately on GitHub</a><a className="button secondary" href="https://github.com/Mighiana/BlastRadius/security" target="_blank" rel="noreferrer">Security policy</a></div></section>
      </> : kind === 'privacy' ? <>
        <section className="panel"><h2>Beta requests, feedback and activity</h2><p>Beta-interest forms collect your name, email and optional workflow details with explicit consent for authorized operator review. Submission does not create an account, guarantee access or send email. Analysis feedback associates your useful/not-useful response and optional text with your account, workspace, project and analysis on the server. Do not paste Terraform, credentials or private infrastructure into either form; free text is not automatically scrubbed.</p><p>These review records become unavailable after 90 days. Physical deletion requires regular operator cleanup and is not automatic. Deleting an analysis or tenant also removes dependent feedback; anonymous beta requests have no account relationship.</p><p>First-party activity records contain fixed milestone names, timestamps and optional internal identifiers. They do not contain source, credentials, names, email, IP addresses or arbitrary browser metadata. The activity summary covers up to 90 days and 100,000 events; capacity pressure removes oldest events. These counts cannot establish willingness to pay.</p></section>
        <section className="panel"><h2>Data processed</h2><p>The service stores account identity, workspace membership, projects, usage records, invitations, session metadata and audit events. Analysis evidence may include resource names, source diffs, policy snapshots, findings, attack paths and suggested HCL patches. Do not upload secrets or unnecessary personal data.</p><p>GitHub integrations store installation and repository IDs, PR references, commit SHAs and publication state. The provider receives checks and comments on authorized repositories. Public demo reports use synthetic fixtures.</p></section>
        <section className="panel"><h2>Retention and deletion</h2><p>Default evidence retention is 7 days for Free, 90 for Pro and 365 for Team. Enterprise limits are configurable. The current workspace entitlement applies at read time; evidence beyond that window is unavailable. Physical cleanup is an operator task, not a claim of immediate secure erasure.</p><p>Deleting an analysis removes its stored report and associated evidence, without refunding accepted-job usage. External copies, GitHub comments, backups and retained delivery records may remain under operator or provider policies. Operators must define backup retention and deletion procedures.</p><Link className="button secondary" to="/billing">Check workspace retention</Link></section>
        <section className="panel"><h2>Operator responsibilities and requests</h2><p>The deployment operator is the data controller and defines hosting region, subprocessors, lawful bases and incident procedures for their deployment. Contact your deployment operator for account access or deletion requests.</p><p>Invitation secrets are passed through a URL fragment, removed from the address after reading and sent only in the acceptance POST body. They are not stored in browser storage. Sign in first and reopen your original invitation.</p></section>
      </> : <>
        <section className="panel"><h2>Beta service and eligibility</h2><p>Use BlastRadius only with infrastructure and repositories you are authorized to analyze. Keep account access and privately delivered invitation links secure. Do not submit secrets, malicious content or attempt to bypass tenant boundaries.</p><p>The service is a commercial beta. Free access and operator-granted paid-plan entitlements are subject to configured limits. Proposed paid prices are informational; payments, checkout and automatic subscription activation are unavailable.</p></section>
        <section className="panel"><h2>Human review remains required</h2><p>Reports provide evidence within a bounded static model. They are not a security warranty, compliance certification or assurance against compromise. Review coverage, policy, recommendations and any patches before applying changes. BlastRadius does not deploy infrastructure for you.</p></section>
        <section className="panel"><h2>Beta scope</h2><p>The contracting entity, support channels, service commitments, liability, governing law and dispute procedures are those of your deployment operator. No production SLA or payment commitment is created during the beta.</p></section>
      </>}
      <nav className="button-row" aria-label="Trust pages"><Link className="button secondary" to="/security">Security</Link><Link className="button secondary" to="/privacy">Privacy</Link><Link className="button secondary" to="/terms">Terms</Link></nav>
    </div>
  </div>;
}
